import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { Questions } from '../shared/manage-test.model';
import { AptiQuestions } from '../shared/aptitude.model';
import { FormBuilder, FormGroup } from '@angular/forms';
@Component({
  selector: 'app-manage-tests',
  templateUrl: './manage-tests.component.html',
  styleUrls: ['./manage-tests.component.css'],
})
export class ManageTestsComponent implements OnInit {
  formValue!: FormGroup;
  AptiformValue!: FormGroup;
  questionData10: any =[];
  questionData12: any =[];
  questionDataApti: any =[];
  isAdded!: boolean;
  isUpdated!: boolean;
  queObj: Questions = new Questions();
  aptiQueObj: AptiQuestions = new AptiQuestions();
  enable10: boolean = false;
  enable12: boolean = false;
  enableApti: boolean = false;
  currentQueForUpdate="";
  currentAptiQueForUpdate="";
  constructor(private api: ApiService, private formBuilder: FormBuilder) {}

  ngOnInit(): void {
    this.formValue = this.formBuilder.group({
      queID: [''],
      question: [''],
      questionMarathi: [''],
      questionField: [''],
    });
    this.AptiformValue = this.formBuilder.group({
      qID: [''],
      question: [''],
      // questionMarathi: [''],
      option1: [''],
      option2: [''],
      option3: [''],
      option4: [''],
      answer: [''],
      questionType: [''],
    });
    this.getAllQuestions();
  }
  activateAdd() {
    this.formValue.reset();
    this.isAdded = true;
    this.isUpdated = false;
  }
  getAllQuestions() {
    this.questionData10=[];
    this.questionData12=[];
    this.questionDataApti=[];
    this.api.showQuestions10().subscribe((res) => {
      // this.questionData10 = res;
      for(const r in res){
        res[r].id=r;
        this.questionData10.push({ ...res[r], quetsionID:r});
        // console.log(res[r]);
      }
      // console.log(this.questionData10);
    });

    this.api.showQuestions12().subscribe((res) => {
      // this.questionData12 = res;
      for(const r in res){
        res[r].id=r;
        this.questionData12.push({ ...res[r], quetsionID:r});
        // console.log(res[r]);
      }
      // console.log(res);
    });

    this.api.sectionBQuestions().subscribe((res)=>{
      // this.questionDataApti = res.questionDetails;
      for(const r in res){
        res[r].id=r;
        this.questionDataApti.push({ ...res[r], qID:r});
        // console.log(res[r]);
      }
      // console.log(res);
    })
  }

  manage10() {
    this.enable10 = true;
    this.enable12 = false;
    this.enableApti=false;
  }

  manage12() {
    this.enable10 = false;
    this.enable12 = true;
    this.enableApti = false;
  }

  manageApti(){
    this.enable10 = false;
    this.enable12 = false;
    this.enableApti = true;
  }

  addQuestions() {
    // this.queObj.quetsionID = 'autogenerated';
    this.queObj.question = this.formValue.value.question;
    this.queObj.questionMarathi = this.formValue.value.questionMarathi;
    this.queObj.questionField = this.formValue.value.questionField;
    if (this.enable10) {
      this.queObj.std = '10';
      this.api.addQuestions10(this.queObj).subscribe((res) => {
        // console.log(res);
        alert('added question');
        let closeBtn = document.getElementById('close');
        closeBtn?.click();
        this.getAllQuestions();
      });
    } else if (this.enable12) {
      this.queObj.std = '12';
      this.api.addQuestions12(this.queObj).subscribe((res) => {
        // console.log(res);
        alert('added question');
        let closeBtn = document.getElementById('close');
        closeBtn?.click();
        this.getAllQuestions();
      });
    }
  }

  addAptiQuestions() {
    this.aptiQueObj.qID = "0";
    this.aptiQueObj.que = this.AptiformValue.value.question;
    this.aptiQueObj.option1 = this.AptiformValue.value.option1;
    this.aptiQueObj.option2 = this.AptiformValue.value.option2;
    this.aptiQueObj.option3 = this.AptiformValue.value.option3;
    this.aptiQueObj.option4 = this.AptiformValue.value.option4;
    this.aptiQueObj.answer = this.AptiformValue.value.answer;
    this.aptiQueObj.queType = this.AptiformValue.value.questionType;
    this.api.addQuestionsB(this.aptiQueObj).subscribe((res) => {
      // console.log(res);
      alert('added question');
      let closeBtn = document.getElementById('closeApti');
      closeBtn?.click();
      this.getAllQuestions();
    });
  }

  onEdit(row: any) {
    this.queObj.quetsionID = row.queID;
    this.formValue.controls['queID'].setValue(row.quetsionID);
    this.formValue.controls['question'].setValue(row.question);
    this.formValue.controls['questionMarathi'].setValue(row.questionMarathi);
    this.formValue.controls['questionField'].setValue(row.questionField);
    if (this.enable10) {
      this.queObj.std = '10';
    } else if (this.enable12) {
      this.queObj.std = '12';
    }
    this.isAdded = false;
    this.isUpdated = true;
    this.currentQueForUpdate=row.quetsionID;
    // console.log("button clicked ", this.currentQueForUpdate);
  }

  onEditApti(row: any) {
    // this.aptiQueObj.qID = row.qID;
    this.currentAptiQueForUpdate=row.qID;
    this.AptiformValue.controls['question'].setValue(row.que);
    this.AptiformValue.controls['option1'].setValue(row.option1);
    this.AptiformValue.controls['option2'].setValue(row.option2);
    this.AptiformValue.controls['option3'].setValue(row.option3);
    this.AptiformValue.controls['option4'].setValue(row.option4);
    this.AptiformValue.controls['answer'].setValue(row.answer);
    this.AptiformValue.controls['questionType'].setValue(row.queType);
    this.isAdded = false;
    this.isUpdated = true;
  }

  editAptiQuestion() {
    this.aptiQueObj.qID = this.currentAptiQueForUpdate;
    this.aptiQueObj.que = this.AptiformValue.value.question;
    this.aptiQueObj.option1 = this.AptiformValue.value.option1;
    this.aptiQueObj.option2 = this.AptiformValue.value.option2;
    this.aptiQueObj.option3 = this.AptiformValue.value.option3;
    this.aptiQueObj.option4 = this.AptiformValue.value.option4;
    this.aptiQueObj.answer = this.AptiformValue.value.answer;
    this.aptiQueObj.queType = this.AptiformValue.value.questionType;
    this.api.updateQuestionB(this.aptiQueObj, this.currentAptiQueForUpdate).subscribe((res) => {
      alert('Updated Successfully');
      let closeBtn = document.getElementById('closeApti');
      closeBtn?.click();
      this.getAllQuestions();
    });
  }

  editQuestion() {
    this.queObj.quetsionID = this.currentQueForUpdate;
    this.queObj.question = this.formValue.value.question;
    this.queObj.questionMarathi = this.formValue.value.questionMarathi;
    this.queObj.questionField = this.formValue.value.questionField;
    if(this.enable10){
      this.api.updateQuestion10(this.queObj, this.currentQueForUpdate).subscribe((res) => {
        alert('Updated Successfully');
        let closeBtn = document.getElementById('close');
        closeBtn?.click();
        this.getAllQuestions();
      });
      // console.log(this.currentQueForUpdate);
    }
    else if(this.enable12){
      this.api.updateQuestion12(this.queObj, this.currentQueForUpdate).subscribe((res) => {
        alert('Updated Successfully');
        let closeBtn = document.getElementById('close');
        closeBtn?.click();
        this.getAllQuestions();
      });
    }
  }

  deleteQuestion10(row: any) {
    let clickedYes = confirm('Are you sure want to delete');
    if (clickedYes) {
      this.api.delQue10(row.quetsionID).subscribe((res) => {
        alert('Deleted Successfully');
        this.getAllQuestions();
      });
    }
  }
  deleteQuestion12(row: any) {
    let clickedYes = confirm('Are you sure want to delete');
    if (clickedYes) {
      this.api.delQue12(row.quetsionID).subscribe((res) => {
        alert('Deleted Successfully');
        this.getAllQuestions();
      });
    }
  }

  deleteAptiQuestion(row: any) {
    let clickedYes = confirm('Are you sure want to delete');
    if (clickedYes) {
      this.api.delQueB(row.qID).subscribe((res) => {
        alert('Deleted Successfully');
        this.getAllQuestions();
      });
    }
  }
}
